#!/usr/bin/env node
// Writes .github/ISSUE_TEMPLATE/submit-game.yml with dropdown options from the taxonomies. Run after any taxonomy
// change: node scripts/issue-form.mjs (a test fails when the file on disk is stale).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse, stringify } from 'yaml';
import { allowedList } from './profiles.mjs';

export const FORM_PATH = '.github/ISSUE_TEMPLATE/submit-game.yml';

export function issueForm(dir = '.') {
  const names = (kind) => parse(readFileSync(join(dir, 'taxonomies', `${kind}.yaml`), 'utf8')).terms.map((t) => t.name);
  const input = (id, label, description, required = false) => ({ type: 'input', id, attributes: { label, ...(description ? { description } : {}) }, validations: { required } });
  const dropdown = (id, label, options, { multiple = false, required = false } = {}) => ({ type: 'dropdown', id, attributes: { label, multiple, options }, validations: { required } });
  return {
    name: 'Submit a game',
    description: 'Add an AI-made game to GamesByAI. Every submission is reviewed before it goes live.',
    title: 'Submit: ',
    labels: ['submission'],
    body: [
      { type: 'markdown', attributes: { value: 'Everything you enter here is public. Please do not include an email address.' } },
      input('play_url', 'Play URL', 'The https link where the game runs in a browser', true),
      input('repo_url', 'Repository (optional)', 'https://github.com/owner/repo'),
      input('title', 'Game title', '', true),
      input('creator', 'Creator name', '', true),
      input('profile_url', 'Profile link (optional)', `A link to your profile on ${allowedList()}. It shows on your game page.`),
      dropdown('genres', 'Genres', names('genres'), { multiple: true, required: true }),
      dropdown('players', 'Players', ['Single player', 'Local multiplayer', 'Online multiplayer'], { required: true }),
      dropdown('ai_share', 'How much of the code did AI write?', ['All of it', 'Most of it', 'Some of it'], { required: true }),
      dropdown('models', 'AI models used', ['Not sure', ...names('models')], { multiple: true }),
      dropdown('tools', 'AI tools used', ['Not sure', ...names('tools')], { multiple: true }),
      dropdown('engine', 'Engine or framework', ['Not sure', ...names('engines')]),
      input('other_terms', 'Other AI models, tools or engine (optional)', "AI models, tools or an engine missing above, with a link to the maker's page if you have one."),
      { type: 'textarea', id: 'how_made', attributes: { label: 'How you made it (600 characters max)' }, validations: { required: true } },
      {
        type: 'checkboxes',
        id: 'permission',
        attributes: { label: 'Permission', options: [{ label: "I made this game or have the creator's permission, and I agree to the editorial policy.", required: true }] },
      },
    ],
  };
}

export const renderForm = (dir = '.') => `# Generated by scripts/issue-form.mjs from the taxonomies. Do not edit by hand.\n${stringify(issueForm(dir), { lineWidth: 0 })}`;

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync('.github/ISSUE_TEMPLATE', { recursive: true });
  writeFileSync(FORM_PATH, renderForm('.'));
  console.log(`wrote ${FORM_PATH}`);
}
